[build]
  # Diretório que será publicado (relativo à raiz do repositório)
  publish = "."

  # Comandos para construir o projeto
  command = ""

# Configurações de redirecionamento para SPA (Single Page Application)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
