[build]
  # Define o diretório base para o build (relativo ao diretório do `netlify.toml`).
  base = "../data/"

  # Diretório que será publicado (relativo à raiz do projeto).
  publish = "html/"

  # Comando para construir o projeto, executado a partir do diretório 'base'.
  command = "npm install && npm run build:css && npm run build:icon"
